OPCODES = {
    'NOP': 0,
    'LOAD_CONST': 1,
    'STORE_VAR': 2,
    'LOAD_VAR': 3,
    'PRINT': 4,
    'JUMP': 5,
    'JUMP_IF_TRUE': 6,
    'JUMP_IF_FALSE': 7,
    'END': 8,
    'COMPARE_EQ': 9,
    'COMPARE_NEQ': 10,
    'COMPARE_LT': 11,
    'COMPARE_GT': 12,
    'COMPARE_LE': 13,
    'COMPARE_GE': 14,
    'INPUT': 15,
    'ADD': 16,
    'SUB': 17,
    'MUL': 18,
    'DIV': 19,
    'REM': 20,
    'FOR_INIT': 21,
    'FOR_CHECK': 22,
    'FOR_STEP': 23,
    'NEXT': 24,
    'GOSUB': 25,
    'RETURN': 26,
    'READ_VAR': 27,
    'JUMP_IF_TRUE_RETURN': 28,
    'LABEL': 99,
}

KEYWORDS = [
    'LET', 'PRINT', 'INPUT', 'IF', 'THEN', 'GOTO', 'END', 'REM',
    'FOR', 'TO', 'STEP', 'NEXT', 'GOSUB', 'RETURN', 'DIM', 'READ',
    'DATA', 'RESTORE', 'STOP', 'ON', 'DEF', 'FN', 'WHILE', 'WEND',
    'DO', 'LOOP', 'SELECT', 'CASE'
]